In [8]:
import numpy as np

a = np.random.normal(0, 1, (3, 4))
print(a)

b = np.zeros((1,4))
print(b)

Z = [0,1,0,2,3,4,5,-6]
mask = [1 if z > 0 else 0 for z in Z]
print(mask)

relued = np.maximum(0,Z)
print(relued)
print(type(relued))

ran = range(5)
print(type(ran))

[[-0.54990455  1.80776189  0.32661611 -0.35963515]
 [-0.17439532 -1.28381375  0.55105591  0.30699539]
 [ 1.88789828 -0.73442819 -1.30434153 -0.81391294]]
[[0. 0. 0. 0.]]
[0, 1, 0, 1, 1, 1, 1, 0]
[0 1 0 2 3 4 5 0]
<class 'numpy.ndarray'>
<class 'range'>
